//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDavSyncConsole.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://elearning.hslu.ch")]
        public string WebDavServerUrl {
            get {
                return ((string)(this["WebDavServerUrl"]));
            }
            set {
                this["WebDavServerUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/ilias/webdav.php/hslu/ref_696271/TA.PRG2.F0903/Dateiaustausch/Projekt/Gruppe13/")]
        public string WebDavServerPath {
            get {
                return ((string)(this["WebDavServerPath"]));
            }
            set {
                this["WebDavServerPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tfsuter")]
        public string WebDavServerUsername {
            get {
                return ((string)(this["WebDavServerUsername"]));
            }
            set {
                this["WebDavServerUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("JS_+U4JK")]
        public string WebDavServerPassword {
            get {
                return ((string)(this["WebDavServerPassword"]));
            }
            set {
                this["WebDavServerPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Daten\\Sync\\Gruppe 13\\")]
        public string LocalSyncPath {
            get {
                return ((string)(this["LocalSyncPath"]));
            }
            set {
                this["LocalSyncPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ConflictOverWriteFiles {
            get {
                return ((bool)(this["ConflictOverWriteFiles"]));
            }
            set {
                this["ConflictOverWriteFiles"] = value;
            }
        }
    }
}
